apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: wanderlust
data:
  MONGODB_URI: "mongodb://mongo-service/wanderlust"
  REDIS_URL: "redis://redis-service:6379"
  PORT: "8080"
  FRONTEND_URL: "http://PLACEHOLDER_UPDATE_AFTER_ALB"
  ACCESS_COOKIE_MAXAGE: "120000"
  ACCESS_TOKEN_EXPIRES_IN: "120s"
  REFRESH_COOKIE_MAXAGE: "120000"
  REFRESH_TOKEN_EXPIRES_IN: "120s"
  NODE_ENV: "Development"
