apiVersion: v1
kind: Secret
metadata:
  name: wanderlust-secret
  namespace: wanderlust
type: Opaque
data:
  JWT_SECRET: NzBkZDhiMzg0ODZlZWU3MjNjZTI1MDVmNmRiMDZmMWVlNTAzZmRlNWViMDZmYzA0Njg3MTkxYTBlZDY2NWYzZjk4Nzc2OTAyZDJjODlmNmI5OTNiMWM1NzlhODdmZWRhZjU4NGM2OTNhMTA2ZjdjYmYxNmU4YjRlNjdlOWQ2ZGY=
